# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EatingToday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EatingToday
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'SnapKit'
  pod 'Firebase/Storage'
  pod 'BSImagePicker', '~> 3.1'
  pod 'Alamofire'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Cosmos', '~> 23.0'
  pod 'FSCalendar'
  pod 'MaterialComponents/BottomSheet'

end
